### PR TITLE
User Model

### PR DESCRIPTION
**Pull request by Sonali12920**
# Related Issue
Resolved issue #36 

# Proposed Changes
Created a user model 

# Description
Created a User Model, added routes for sign up and sign in and tested it. It properly worked.

# Checklist
- [ ] Clean code  
- [ ] Documentation
- [ ] Proper Readme.md

# Screenshots
- Original
- Updated

# Additional Info or Context (if any)

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hi @Sonali12920 

Good Work! Can you post some screenshots of your Postman showing the APIs in work?

**Comment by Sonali12920** [comment]
Signing up and received the token 
Screenshot (531)

Signing in and received the same token
Screenshot (547)

Database
Screenshot (549)

**Comment by aarushivij** [comment]
Hey,
Great work @Sonali12920 and @saloniankita 
A few comments from my side. Tagging @HarshCasper , so that he too can verify the same.
1)Please add new line in the end of the files. Check [this](https://thoughtbot.com/blog/no-newline-at-end-of-file) for a bit of a history on this.
2) All the above files should be in [server](https://github.com/HarshCasper/AllNotes/tree/main/server) folder, as that is the folder for backend.
3) No need to make [app.js](https://github.com/HarshCasper/AllNotes/blob/91ae2ae6a9f7bf6513f7c589be4aa55841a8c1eb/app.js). There is already [index.js](https://github.com/HarshCasper/AllNotes/blob/main/server/index.js)  in server folder. Add the contents of app.js there.
4) Similarly there is one [package.json](https://github.com/HarshCasper/AllNotes/blob/main/server/package.json) in the server folder. Add the dependencies in that file.

**Comment by Sonali12920** [comment]
Done all the changes and made another PR because of the merge conflicts. You can find the new PR [here](https://github.com/HarshCasper/AllNotes/pull/44). Closing this pr.

**Pull request closed without merging**
