### PR TITLE
Feat:Logo Designs

### PR DESCRIPTION
**Pull request by MudraSurana**
application.

# Related Issue
- issue goes here

# Proposed Changes
- change 1
- change 2

# Description

# Checklist
- [ ] Clean code
- [ ] Documentation
- [ ] Proper Readme.md

# Screenshots
- Original
- Updated

# Additional Info or Context (if any)

### CODE REVIEW

**Review by saloniankita — COMMENTED** [review]
Looks good to me @HarshCasper 
Both of them seem quite good and can be used as Favicon as well as for Splash screen.

**Comment by HarshCasper** [comment]
I'm ready to merge the same. Thanks @MudraSurana for the PR and @saloniankita for the review! 

Just few tiny changes: 

- Keep the Logo in the `design/logo-design` directory 
- Change the Commit message to the standard we are following. It should be `Feat: Add Logo Designs`
- If you don't know how to change the last commit message, please do using this command: 

image

**Comment by HarshCasper** [comment]
Hi @MudraSurana 

Are you still working on it?

**Comment by MudraSurana** [comment]
Yes,I just have to make the pull request with the changes you told.Will do
it today.

**Comment by MudraSurana** [comment]
I am creating a new pull request, with the suggested changes.

**Pull request closed without merging**
